### ISSUE TITLE
聚合签名怎么实现的？

### ISSUE THREAD

**Issue by lightshine001** [HuobiGroup/huobi-chain#10]
看了你们的代码和overlord的开源代码，没有找到宣称的聚合签名具体实现。只有简单接口而已
    fn aggregate_signatures(
        &self,
        _signatures: Vec<Bytes>,
        _voters: Vec<Bytes>,
    ) -> Result<Bytes, Box<dyn Error + Send>> {
        Ok(Bytes::new())
    }

    fn verify_aggregated_signature(
        &self,
        _aggregated_signature: AggregatedSignature,
    ) -> Result<(), Box<dyn Error + Send>> {
        Ok(())
    }

**Comment by KaoImin** [comment]
你好，聚合签名目前没有实现，只是预留了接口，我们将会在下一阶段的开发中时间聚合签名的功能。Thanks
