### ISSUE TITLE
当网络环境导致当交易超时时候，请问针对 Mempool 中被抛弃的交易是否有重试打包机制？还是无效的交易就永远丢弃了？

### ISSUE THREAD

**Issue by gotopath** [HuobiGroup/huobi-chain#3]
当网络环境导致当交易超时时候，请问针对 Mempool 中被抛弃的交易是否有重试打包机制？还是无效的交易就永远丢弃了？

**Comment by rev-chaos** [comment]
当交易超时后，该交易被视为无效，会被 Mempool永远 抛弃，用户的客户端会收到超时通知，可以决定是否重新发送交易（超时需要重新设置）。

**Comment by gotopath** [comment]
Get，这样的话用户转账之后还需要再关注是否成功打包哦。
