### ISSUE TITLE
[ProtocolError] Kind: API Error: IntoU64(ParseIntError { kind: InvalidDigit }):

### ISSUE THREAD

**Issue by MyHbWallet** [HuobiGroup/huobi-chain#41]
**What happened**:
创建assets的时候发生错误
**What you expected to happen**:
 const hash = await client.sendTransaction(signed_tx);
**How to reproduce it (as minimally and precisely as possible)**:
 利用账号签名没有问题，调用sendTransaction会返回
`(node:2624) UnhandledPromiseRejectionWarning: Error: [ProtocolError] Kind: API Error: IntoU64(ParseIntError { kind: InvalidDigit }): {"response":{"data":null,"errors":[{"message":"[ProtocolError] Kind: API Error: IntoU64(ParseIntError { kind: InvalidDigit })","locations":[{"line":2,"column":3}],"path":["sendTransaction"]}],"status":200},"request":{"query":"mutation sendTransaction($inputRaw: InputRawTransaction!, $inputEncryption: InputTransactionEncryption!) {\n  sendTransaction(inputRaw: $inputRaw, inputEncryption: $inputEncryption)\n}\n","variables":{"inputEncryption":{"pubkey":"0x03c94c0a0c925816127841677600fbbb6f58f9a68dfdf9367cd34f60bc6fa76df9","signature":"0xdeb97d34886150d99a9f319f60757760aa7b996fe57025b110bad7d6a2e4db67474cdc5d83577579a54e7241c9e29f40ba6584a3143fd77751ccfe4f0946f579","txHash":"0x21bda1c335386bf750498d30a8f5899a29559f1a388123bd12c4573f90e5f464"},"inputRaw":{"chainId":"0xb6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036","cyclesLimit":"0xffff","cyclesPrice":"0xffff","method":"create_asset","nonce":"0x67f8f41e60a587fff54d5d096f1140d5b3a1e113aaf0146f0860847327b54e3b","payload":"{\"name\":\"LOVE_COIN\",\"symbol\":\"LUV\",\"supply\":1314}","serviceName":"asset","timeout":"0x0NaN"}}}}
    at GraphQLClient.<anonymous> (D:\2020\myhbwallet\node_modules\graphql-request\dist\src\index.js:116:35)
    at step (D:\2020\myhbwallet\node_modules\graphql-request\dist\src\index.js:40:23)
    at Object.next (D:\2020\myhbwallet\node_modules\graphql-request\dist\src\index.js:21:53)
    at fulfilled (D:\2020\myhbwallet\node_modules\graphql-request\dist\src\index.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
**Anything else we need to know?**:

**Environment**:

- Huobi-Chain version or commit hash (`Huobi-Chain -V`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by homura** [comment]
Hello，请问使用的 sdk 版本是否是最新的 0.7.0-alpha.6 呢？方便将生辰 `signed_tx` 代码展示一下吗？

看起来这个错误是由于使用了一个错误的 `timeout` 导致的
> timeout":"0x0NaN"

以下代码片段演示如何正确的发出一笔交易

```javascript
const { Muta } = require('./build/main');

const client = new Muta().client();
const account = Muta.accountFromPrivateKey(
  '0x1000000000000000000000000000000000000000000000000000000000000000',
);

async function main() {
  const rawTransaction = await client.composeTransaction({
    serviceName: 'asset',
    method: 'create_asset',
    payload: {
      supply: 1000000,
      name: 'LOVE_COIN',
      symbol: 'LUV',
    },
  });
  const signedTransaction = account.signTransaction(rawTransaction);
  const txHash = await client.sendTransaction(signedTransaction);

  console.log(txHash);
}

main();

```

**Comment by MyHbWallet** [comment]
"muta-sdk": "^0.7.0-alpha.6"

`{
  chainId: '0xb6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036',
  cyclesLimit: '0xffff',
  cyclesPrice: '0xffff',
  method: 'create_asset',
  nonce: '0x8d357e05057d7fef17637494f8cf9fe6e50136cb2ab38aa8340dccd2d9e107d8',
  payload: '{"name":"LOVE_COIN","symbol":"LUV","supply":1314}',
  pubkey: '0x02c2005d049238517b15d69d95298d67b00110b9c868d44d9381163cf05ab71628',
  serviceName: 'asset',
  signature: '0x4c9a03af4b2acb085530723959c35bd0bfba60e5229efd553e73809adf5843f52b0cb126c30514ba2d9befe6f76170745e4985dbd24748a5999ca968ad256e8c',
  timeout: '0x0NaN',
  txHash: '0x6af83e0a2487e254fefe1c9a04018d34e86e46a10689b2cf2d5f36b83ef09b6d'
}`

**Comment by homura** [comment]
签名的内容确实是有异常的地方，在 `timeout` 这个字段内出现了 NaN 的错误

方便展示一下如何生成 `signed_tx` 的 javascript 代码吗

**Comment by MyHbWallet** [comment]
`const { Muta, AssetService } = require('muta-sdk')
const Wallet = Muta.hdWallet;

const muta = new Muta({
  /**
   * 通常是在genesis.toml里包含有默认的chain_id
   * 在这个例子中我们假设0xb6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036是你要访问的链的ChainId
   */
  chainId:
    '0xb6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036',

  /**
   *  接下来我们给出 GraphQL API uri. endpoint 是用来和链进行 RPC 交互的 URI,
   *  http://127.0.0.1:8000/graphql 是默认的 endpoint 是用来和链进行 RPC 交互的 URI,
   *  你可以在 config.toml 文件下的 [graphql] 部分找到 endpoint 的配置
   */
  endpoint: 'http://192.168.31.94:8000/graphql',

  /**
   * timeout_gap 表示一笔交易发出后，最多允许几个块的延迟.如果随着链的进行, block 超出了
   * timeout_gap 的设置但是交易仍然没有上链,那么这笔交易就被认为无效了.
   * 比起以太坊的 txpool 的不确定性,Huobi-chain提供了tx及时性的检测和保障.
   * timeoutGap 并没有默认值,但是 js-sdk 预设为20,你可以所以更改
   */
  timeoutGap: Muta.DEFAULT_TIMEOUT_GAP,
});
const client = muta.client();
const account = Muta.accountFromPrivateKey(
  '0x1000000000000000000000000000000000000000000000000000000000000000',
);

async function main() {
  const rawTransaction = await client.composeTransaction({
    serviceName: 'asset',
    method: 'create_asset',
    payload: {
      supply: 1000000,
      name: 'LOVE_COIN',
      symbol: 'LUV',
    },
  });
  const signedTransaction = account.signTransaction(rawTransaction);
  const txHash = await client.sendTransaction(signedTransaction);

  console.log(txHash);
}

main();`

**Comment by MyHbWallet** [comment]
`const { Muta, AssetService } = require('muta-sdk')
const Wallet = Muta.hdWallet;

const muta = new Muta({
  /**
   * 通常是在genesis.toml里包含有默认的chain_id
   * 在这个例子中我们假设0xb6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036是你要访问的链的ChainId
   */
  chainId:
    '0xb6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036',

  /**
   *  接下来我们给出 GraphQL API uri. endpoint 是用来和链进行 RPC 交互的 URI,
   *  http://127.0.0.1:8000/graphql 是默认的 endpoint 是用来和链进行 RPC 交互的 URI,
   *  你可以在 config.toml 文件下的 [graphql] 部分找到 endpoint 的配置
   */
  endpoint: 'http://192.168.31.94:8000/graphql',

  /**
   * timeout_gap 表示一笔交易发出后，最多允许几个块的延迟.如果随着链的进行, block 超出了
   * timeout_gap 的设置但是交易仍然没有上链,那么这笔交易就被认为无效了.
   * 比起以太坊的 txpool 的不确定性,Huobi-chain提供了tx及时性的检测和保障.
   * timeoutGap 并没有默认值,但是 js-sdk 预设为20,你可以所以更改
   */
  timeoutGap: Muta.DEFAULT_TIMEOUT_GAP,
});
const client = muta.client();
const account = Muta.accountFromPrivateKey(
  '0x1000000000000000000000000000000000000000000000000000000000000000',
);

async function main() {
  const rawTransaction = await client.composeTransaction({
    serviceName: 'asset',
    method: 'create_asset',
    payload: {
      supply: 1000000,
      name: 'LOVE_COIN',
      symbol: 'LUV',
    },
  });
  const signedTransaction = account.signTransaction(rawTransaction);
  const txHash = await client.sendTransaction(signedTransaction);

  console.log(txHash);
}

main();`

**Comment by homura** [comment]
Sorry, 文档中的示例代码有些过期

```diff
const muta = new Muta({
  chainId: '0xb6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036',

  endpoint: 'http:/127.0.0.1:8000/graphql',
+ // 现在的 DEFAULT_TIMEOUT_GAP 已经不再直接挂载在 Muta 类
+ // 可以删除这行代码
-  timeoutGap: Muta.DEFAULT_TIMEOUT_GAP,

+ // 或者定义与正在跑的链同样的 timeoutGap 配置值
+ timeoutGap:  20
});
```
