### ISSUE TITLE
https://huobigroup.github.io/huobi-chain/#/getting_started 编辑错误

### ISSUE THREAD

**Issue by owenSai** [HuobiGroup/huobi-chain#53]
使用示例># 查询发行者余额
await client.queryService({serviceName: 'asset', method: 'get_balance', payload: JSON.stringify({asset_id: MT.responce.net.id, user: account.address})}) // MT.responce.net.id 应该为MT.responce.ret.id

**Comment by huwenchao** [comment]
已修复：<https://github.com/HuobiGroup/huobi-chain/commit/01f2be1e5e0355f402150a0d29caaedd96ecf61f>

感谢您的反馈！
