### ISSUE TITLE
怎么测试huobi-chain?

### ISSUE THREAD

**Issue by BenxiangGe** [HuobiGroup/huobi-chain#7]
请教，如何测试huobi-chain? 比如怎么mint，transfer，运行智能合约？thanks

**Comment by yejiayu** [comment]
目前 huobi-chain 还不支持合约。

转账操作你可以先按照[文档](https://github.com/HuobiGroup/huobi-chain/blob/master/docs/getting_started.md)把节点跑起来后访问 http://localhost:8000/graphiql ，通过 GraphQL IDE 执行转账。

通过 GraphQL IDE 可以查看到，目前转账支持两种接口
- sendTransferTransaction
- sendUnsafeTransferTransaction

由于还没有对于交易序列化和签名规范的说明文档，建议你先使用 `sendUnsafeTransferTransaction ` 测试转账，这个接口会根据你发送的 raw tx 和 private key 自动的帮你做签名，这也是我们内部测试经常使用的接口，

Thanks

**Comment by zhangdavids** [comment]
:clap:

**Comment by BenxiangGe** [comment]
@yejiayu 

谢谢回复。能否给个GraphQL 查询语句的示例？GraphQL 的语法看起来很奇怪的。比如getLatestEpoch，或者getBalance等。sendUnsafeTransferTransaction 还是太复杂了。thanks。

**Comment by homura** [comment]
Hi, @BenxiangGe 
可以尝试下面的语句
```graphql
query {
  getLatestEpoch {
    header {
      chainId,
      epochId
    }
  }
}
```

graphiql 有很强大的提示补足功能，这边有相关[演示视频](https://vimeo.com/371535246)
